# Generated by Django 5.0.2 on 2024-02-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Блоги', 'verbose_name_plural': 'Блоги'},
        ),
    ]
