# Generated by Django 5.0.2 on 2024-03-02 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2024, 3, 2, 12, 38, 53, 561052, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
    ]
